-- CreateEnum
CREATE TYPE "MailingStatus" AS ENUM ('PROCESSING', 'COMPLETED', 'CANCELLED');

-- AlterTable
ALTER TABLE "Mailing" ADD COLUMN     "failed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "progress" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "status" "MailingStatus" NOT NULL DEFAULT 'PROCESSING',
ADD COLUMN     "statusChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
