export default interface Group {
    "FormOfEducationGid": number,
    "FormOfEducationOid": number,
    "SpecialityGid": number,
    "SpecialityOid": number,
    "YearOfEducation": number,
    "amount": number,
    "chairGid": number,
    "chairOid": number,
    "course": number,
    "faculty": string,
    "facultyGid": number,
    "facultyOid": number,
    "formOfEducation": string,
    "groupGUID": string,
    "groupGid": number,
    "groupOid": number,
    "groupUID": any | null,
    "kindEducation": number,
    "name": string,
    "number": string,
    "plannedamount": number,
    "speciality": string
}
