import {Center} from "@mantine/core";

export default function GlobalLoading() {
    // [ldio] generated by https://loading.io
    return <div style={{
        position: 'fixed',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
    }}>
        <img src={'/loading-gear.gif'} alt={'gear'} width={100} height={100}/>
        <Center>Загрузка...</Center>
    </div>
}